# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: latency.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'latency.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlatency.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x8e\x07\n\x0fLatencyProtobuf\x12,\n\x06prefix\x18\x01 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12/\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12,\n\x06result\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12.\n\x08provider\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12,\n\x06region\x18\x05 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x30\n\ndataCenter\x18\x06 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12,\n\x06target\x18\x07 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12.\n\x08targetIP\x18\x08 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12+\n\x06\x61vgRTT\x18\t \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12+\n\x06minRTT\x18\n \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12+\n\x06maxRTT\x18\x0b \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12+\n\x06stdRTT\x18\x0c \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12.\n\tnoSuccess\x18\r \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12/\n\nnoFailures\x18\x0e \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12.\n\x08protocol\x18\x0f \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12,\n\x06origin\x18\x10 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12)\n\x04rtts\x18\x11 \x03(\x0b\x32\x1b.google.protobuf.Int32Value\x12/\n\terrorCode\x18\x12 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x31\n\x0b\x65rrorString\x18\x13 \x01(\x0b\x32\x1c.google.protobuf.StringValueb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'latency_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LATENCYPROTOBUF']._serialized_start=50
  _globals['_LATENCYPROTOBUF']._serialized_end=960
# @@protoc_insertion_point(module_scope)
