# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: olap.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'olap.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nolap.proto\x12\x15\x65\x65ro.olapapi.protobuf\x1a\x1egoogle/protobuf/wrappers.proto\"\\\n GetDnsRttAggregatedEventsRequest\x12\x12\n\nnetwork_id\x18\x01 \x01(\x05\x12\x12\n\nstart_time\x18\x02 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x03\"\xc8\x01\n!GetDnsRttAggregatedEventsResponse\x12\x64\n\"dns_rtt_aggregated_events_response\x18\x01 \x01(\x0b\x32\x36.eero.olapapi.protobuf.PDnsRttAggregatedEventsResponseH\x00\x12\x33\n\x05\x65rror\x18\x02 \x01(\x0e\x32\".eero.olapapi.protobuf.POlapErrorsH\x00\x42\x08\n\x06result\"p\n\x1fPDnsRttAggregatedEventsResponse\x12M\n\x15\x64ns_aggregated_events\x18\x01 \x03(\x0b\x32..eero.olapapi.protobuf.PDnsRttAggregatedEvents\"\xbe\x02\n\x17PDnsRttAggregatedEvents\x12\x12\n\nnetwork_id\x18\x01 \x01(\x05\x12\x0e\n\x06rtt_10\x18\x02 \x01(\x03\x12\x0e\n\x06rtt_30\x18\x03 \x01(\x03\x12\x0f\n\x07rtt_100\x18\x04 \x01(\x03\x12\x0f\n\x07rtt_150\x18\x05 \x01(\x03\x12\x0f\n\x07rtt_300\x18\x06 \x01(\x03\x12\x0f\n\x07rtt_500\x18\x07 \x01(\x03\x12\x0f\n\x07rtt_800\x18\x08 \x01(\x03\x12\x10\n\x08rtt_1600\x18\t \x01(\x03\x12\x11\n\trtt_16000\x18\n \x01(\x03\x12\x13\n\x0bhighest_rtt\x18\x0b \x01(\x01\x12H\n\x14tls_server_providers\x18\x0c \x03(\x0b\x32*.eero.olapapi.protobuf.PTlsServiceProvider\x12\x16\n\x0e\x65xecution_date\x18\r \x01(\x03\"C\n\x13PTlsServiceProvider\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1e\n\x16test_server_ip_address\x18\x02 \x01(\t*G\n\x0bPOlapErrors\x12\x11\n\rUNKNOWN_ERROR\x10\x00\x12\x14\n\x10\x45NTITY_NOT_FOUND\x10\x01\x12\x0f\n\x0b\x42\x41\x44_REQUEST\x10\x02\x32\xa0\x01\n\x0bOLAPService\x12\x90\x01\n\x19GetDnsRttAggregatedEvents\x12\x37.eero.olapapi.protobuf.GetDnsRttAggregatedEventsRequest\x1a\x38.eero.olapapi.protobuf.GetDnsRttAggregatedEventsResponse\"\x00\x42\"\n\x11\x65\x65ro.olapapi.grpcB\x0bOLAPServiceP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'olap_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021eero.olapapi.grpcB\013OLAPServiceP\001'
  _globals['_POLAPERRORS']._serialized_start=870
  _globals['_POLAPERRORS']._serialized_end=941
  _globals['_GETDNSRTTAGGREGATEDEVENTSREQUEST']._serialized_start=69
  _globals['_GETDNSRTTAGGREGATEDEVENTSREQUEST']._serialized_end=161
  _globals['_GETDNSRTTAGGREGATEDEVENTSRESPONSE']._serialized_start=164
  _globals['_GETDNSRTTAGGREGATEDEVENTSRESPONSE']._serialized_end=364
  _globals['_PDNSRTTAGGREGATEDEVENTSRESPONSE']._serialized_start=366
  _globals['_PDNSRTTAGGREGATEDEVENTSRESPONSE']._serialized_end=478
  _globals['_PDNSRTTAGGREGATEDEVENTS']._serialized_start=481
  _globals['_PDNSRTTAGGREGATEDEVENTS']._serialized_end=799
  _globals['_PTLSSERVICEPROVIDER']._serialized_start=801
  _globals['_PTLSSERVICEPROVIDER']._serialized_end=868
  _globals['_OLAPSERVICE']._serialized_start=944
  _globals['_OLAPSERVICE']._serialized_end=1104
# @@protoc_insertion_point(module_scope)
