# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: person.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'person.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cperson.proto\x12\x07\x65xample\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf0\x02\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12(\n\x03\x61ge\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.Int32Value\x12+\n\x05\x65mail\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12+\n\x06phones\x18\x04 \x03(\x0b\x32\x1b.example.Person.PhoneNumber\x12\x30\n\x0clast_updated\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\tis_active\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x1a\x46\n\x0bPhoneNumber\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\'\n\x04type\x18\x02 \x01(\x0e\x32\x19.example.Person.PhoneType\"+\n\tPhoneType\x12\n\n\x06MOBILE\x10\x00\x12\x08\n\x04HOME\x10\x01\x12\x08\n\x04WORK\x10\x02\"2\n\x0ePersonResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'person_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERSON']._serialized_start=91
  _globals['_PERSON']._serialized_end=459
  _globals['_PERSON_PHONENUMBER']._serialized_start=344
  _globals['_PERSON_PHONENUMBER']._serialized_end=414
  _globals['_PERSON_PHONETYPE']._serialized_start=416
  _globals['_PERSON_PHONETYPE']._serialized_end=459
  _globals['_PERSONRESPONSE']._serialized_start=461
  _globals['_PERSONRESPONSE']._serialized_end=511
# @@protoc_insertion_point(module_scope)
